services:
  - type: web
    name: studentease
    env: python
    plan: free
    repo: https://github.com/yourusername/studentease
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && gunicorn --config gunicorn.conf.py app:app
    preDeployCommand: cp -r static/* /opt/render/project/src/static/ || true
    disk:
      name: app-data
      mountPath: /opt/render/project/src
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:////opt/render/project/src/marketplace.db
      - key: SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false